/* Auto-generated by genmsg_cpp for file /home/josh/orocos/orocos/wbc_lwr/msg/RobotState.msg */
#ifndef WBC_LWR_BOOST_SERIALIZATION_ROBOTSTATE_H
#define WBC_LWR_BOOST_SERIALIZATION_ROBOTSTATE_H

#include <boost/serialization/serialization.hpp>
#include <boost/serialization/nvp.hpp>
#include <wbc_lwr/RobotState.h>
#include <ros/common.h>
#if ROS_VERSION_MINIMUM(1,4,0)
#include <std_msgs/Header.h>
#else
#include <roslib/Header.h>
#endif

namespace boost
{
namespace serialization
{

template<class Archive, class ContainerAllocator>
void serialize(Archive& a,  ::wbc_lwr::RobotState_<ContainerAllocator>  & m, unsigned int)
{
    a & make_nvp("header",m.header);
    a & make_nvp("JntPos",m.JntPos);
    a & make_nvp("JntVel",m.JntVel);
    a & make_nvp("JntCmd",m.JntCmd);
}

} // namespace serialization
} // namespace boost

#endif // WBC_LWR_BOOST_SERIALIZATION_ROBOTSTATE_H

