- tasks:
  - type: opspace::TestNormalizedImplicitSurfaceTask
    name: surface
    end_effector: 6
    kp: [  3.0 ]
    kd: [  30.0 ]
    control_point: [ 0, 0, 0.2 ]
    R: 0.25
    T: 8.0
  - type: opspace::TestPureSelectCartPosTask
    name: eesurf
    end_effector: 6
    kp: [   0.0,  0.0 ]
    kd: [   0.0,  0.0 ]
    control_point: [ 0, 0, 0.2 ]
    goalpos: [ 0.50, 0.00 ]
    goalvel: [ 0.0, 0.0 ]
    selection: [1, 1, 0]
  - type: opspace::PureCartPosTask
    name: eepos
    end_effector: 6
    kp: [   0.0,  0.0,  0.0]
    kd: [   5.0,  5.0,  5.0 ]
    control_point: [ 0, 0, 0.2 ]
    goalpos: [ 0.5, 0.0, 0.0 ]
    goalvel: [ 0.0, 0.0, 0.0 ]
  - type: opspace::PureJPosTask
    name: posture
    kp: [   0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0]
    kd: [   3.0,  3.0,  3.0,  3.0,  3.0,  3.0,  3.0]
    goalpos: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

- skills:
  - type: uta_opspace::AttachSurface
    name: attach
    surflimitlow: 1.0
    surflimithigh: 1.25
    slots:
      surface: surface
      eesurf: eesurf
      eepos: eepos
      posture: posture
