- tasks:
  - type: opspace::PureCartPosTask
    name: task
    end_effector: 6
    kp: [  60.0, 60.0, 60.0 ]
    kd: [  10.0, 10.0, 10.0 ]
    control_point: [ 0, 0, 0 ]
    goalpos: [ 0.37, 0.01, 0.87]
  - type: opspace::PureJPosTrjTask
    name: posture
    sigma_threshold: 0.0001
    dt_seconds: 0.0025
    kp: [ 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 ]
    kd: [ 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 ]
    maxvel: [ 1.0 ]
    maxacc: [ 3.0 ] 
  - type: opspace::SelectedJointPostureTask
    name: task2
    kp:   [ 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 ]
    kd:   [ 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 ]
    selection: [ 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0 ] 
    goalpos: [ 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 ]

- skills:
  - type: opspace::TwoTaskSkill
    name: threetask
    slots:
      task1: task
      task2: task2
#      task3: posture
