- tasks:
  - type: opspace::TestNormalizedImplicitSurfaceTask
    name: task
    end_effector: 6
    kp: [   5.0 ]
    kd: [   1.0 ]
    control_point: [ 0.0, 0.0, 0.0]
    R: 0.1
    T: 0.4
  - type: opspace::PureJPosTask
    name: task2
    kp: [   0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0]
    kd: [   0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0]
    goalpos: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

- skills:
  - type: opspace::TwoTaskSkill
    name: threetask
    slots:
      task1: task
      task2: task2
