- tasks:
  - type: opspace::TestNormalizedImplicitSurfaceTask
    name: task
    end_effector: 6
    kp: [   5.0 ]
    kd: [   1.0 ]
    control_point: [ 0.0, 0.0, 0.0]
    R: 0.1
    T: 0.4
  - type: opspace::TestPureSelectCartPosTask
    name: task2
    end_effector: 5
    kp: [   5.0,  5.0 ]
    kd: [   1.0,  1.0 ]
    control_point: [ 0, 0, 0 ]
    goalpos: [ 0.375, 0.00 ]
    goalvel: [ 0.0, 0.0 ]
    selection: [1, 1, 0]

- skills:
  - type: opspace::TwoTaskSkill
    name: threetask
    slots:
      task1: task
      task2: task2
