- tasks:
  - type: opspace::TestNormalizedImplicitSurfaceTask
    name: task
    end_effector: 6
    kp: [  10.0 ]
    kd: [  30.0 ]
    control_point: [ 0.0, 0.0, 0.0]
    R: 0.1
    T: 0.4
  - type: opspace::TestOriSurfaceTask
    name: task2
    end_effector: 6
    kp: [  15.0, 15.0, 15.0]
    kd: [   5.0,  5.0,  5.0 ]
    control_point: [ 0, 0, 0 ]
    R: 0.1
    T: 0.4
    ffacc: [0.0, 0.0, 0.0]
    ffvel: [0.0, 0.0, 0.0]
  - type: opspace::TestPureSelectCartPosTask
    name: task3
    end_effector: 6
    kp: [  30.0, 30.0 ]
    kd: [   5.0,  5.0 ]
    control_point: [ 0, 0, 0 ]
    goalpos: [ 0.5, 0.00 ]
    goalvel: [ 0.0, 0.0 ]
    selection: [1, 1, 0]  
  - type: opspace::PureJPosTask
    name: task4
    kp: [   0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0]
    kd: [   3.0,  3.0,  3.0,  3.0,  3.0,  3.0,  3.0]
    goalpos: [0.0, -0.6, 0.0, 1.57, 0.0, -0.88, 0.0]

- skills:
  - type: opspace::FourTaskSkill
    name: threetask
    slots:
      task1: task
      task2: task2
      task3: task3
      task4: task4
