- tasks:
  - type: opspace::TestNormalizedImplicitSurfaceTask
    name: task
    end_effector: 6
    kp: [   2.0 ]
    kd: [  30.0 ]
    control_point: [ 0, 0, 0.0 ]
    R: 0.25
    T: 8.0
  - type: opspace::PlanarCartPosTrjTask
    name: task2
    end_effector: 6
    kp: [  15.0,  15.0 ]
    kd: [   8.0,   8.0 ]
    control_point: [ 0, 0, 0 ]
    dt_seconds: 0.001
    maxacc: [0.5, 0.5]
    maxvel: [0.5, 0.5]
  - type: opspace::PureJPosTask
    name: task3
    kp: [   0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0]
    kd: [   5.0,  5.0,  5.0,  5.0,  5.0,  5.0,  5.0]
    goalpos: [0.0, -0.6, 0.0, 1.57, 0.0, -0.88,  0.0]

- skills:
  - type: uta_opspace::SurfaceMotion
    name: threetask
    threshold: 0.05
    vel_threshold: 0.10
    eepos: [ 0.50,  0.08,
             0.50, -0.08 ]
    posture: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
	      0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 ]
    ee_num: 2
    slots:
      surface: task
      eepos: task2
      posture: task3
