- tasks:
  - type: opspace::PureCartPosTask
    name: task
    end_effector: 6
    kp: [  60.0, 60.0, 60.0 ]
    kd: [  10.0, 10.0, 10.0 ]
    control_point: [ 0, 0, 0 ]
    goalpos: [ -0.43, -0.04, 0.34]
  - type: opspace::TestMassOptTask
    name: task2
    end_effector: 6
    control_point: [ 0, 0, 0 ]
    kp: 100
    kd: 30
    wmax: 5

- skills:
  - type: opspace::TwoTaskSkill
    name: twotask
    slots:
      task1: task
      task2: task2
