- tasks:
  - type: opspace::TestImplicitSurfaceTask
    name: surface
    end_effector: 5
    kp: [  0.1 ]
    kd: [   0.0 ]
    control_point: [ 0, 0, 0.05 ]
    R: 0.1
    T: 0.4
  - type: opspace::TestOriSurfaceTask
    name: ori
    end_effector: 5
    kp: [   0.1,  0.1, 0.1]
    kd: [   0.0,  0.0, 0.0 ]
    control_point: [ 0, 0, 0.05 ]
    R: 0.1
    T: 0.4
    ffacc: [0.0, 0.0, 0.0]
    ffvel: [0.0, 0.0, 0.0]
  - type: opspace::TestPureSelectCartPosTask
    name: eesurf
    end_effector: 5
    kp: [   0.1,  0.1 ]
    kd: [   0.0,  0.0 ]
    control_point: [ 0, 0, 0.05 ]
    goalvel: [ 0.0, 0.0 ]
    selection: [1, 1, 0]
  - type: opspace::PureCartPosTask
    name: eepos
    end_effector: 5
    kp: [   0.1,  0.1 ]
    kd: [   0.0,  0.0 ]
    control_point: [ 0, 0, 0.05 ]
    goalvel: [ 0.0, 0.0 ]
  - type: opspace::PureJPosTask
    name: posture
    kp: [  0.1, 0.1, 0.1, 0.1, 0.1, 0.1]
    kd: [   0.0,  0.0,  0.0,  0.0,  0.0,  0.0]

- skills:
  - type: uta_opspace::AttachSurface
    name: attach
    eepos: [ 0.475, 0.1,
             0.525, 0.05,
             0.475, 0.00,
             0.425, 0.05,
	     0.475, 0.1,
             0.525, 0.05,
             0.475, 0.00,
             0.425, 0.05,
	     0.475, 0.1,
             0.525, 0.05,
             0.475, 0.00,
             0.425, 0.05 ]     
    defposture: [0.0, 0.0, 0.0, 1.5708, 0.0, 0.0]
    threshold: 0.01
    vel_threshold: 0.10
    ee_num: 2
    zoffset: 0.45
    zamp: 0.10
    surflimit: 0.3
    slots:
      surface: surface
      ori: ori
      eesurf: eesurf
      eepos: eepos
      posture: posture
