- tasks:
  - type: opspace::TestImplicitSurfaceTask
    name: task
    end_effector: 5
    kp: [  10.0 ]
    kd: [   0.0 ]
    control_point: [ 0, 0, 0 ]
    R: 0.5
    T: 0.4
  - type: opspace::TestPureSelectCartPosTask
    name: task2
    end_effector: 5
    kp: [  10.0, 10.0 ]
    kd: [   0.0,  0.0 ]
    control_point: [ 0, 0, 0 ]
    goalpos: [ 0.45, -0.25 ]
    goalvel: [ 0.0, 0.0 ]
    selection: [1, 1, 0]
  - type: opspace::PureJPosTask
    name: task3
    kp: [  1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
    kd: [   0.0,  0.0,  0.0,  0.0,  0.0,  0.0]
    goalpos: [0.0, 0.0, 0.0, 0.0, 0.0, 1.57]

- skills:
  - type: opspace::ThreeTaskSkill
    name: threetask
    slots:
      task1: task
      task2: task2
      task3: task3
