- tasks:
  - type: opspace::PureCartPosTask
    name: task
    end_effector: 5
    kp: [   0.1,  0.1,  0.1 ]
    kd: [   0.0,  0.0,  0.0 ]
    control_point: [ 0, 0, 0.05 ]
    goalpos: [ 0.25, 0.25, 0.3]
  - type: opspace::PureJPosTask
    name: task2
    #kp: [   0.1,  0.1,  0.1, 0.1, 0.1, 0.1]
    kp: [   1.0,  1.0,  1.0, 1.0, 1.0, 1.0]
    kd: [   0.0,  0.0,  0.0,  0.0,  0.0,  0.0]
    goalpos: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

- skills:
  - type: opspace::TwoTaskSkill
    name: twotask
    slots:
      task1: task
      task2: task2
