- tasks:
  - type: opspace::PureCartPosTask
    name: task
    end_effector: 5
    kp: [  10.0, 10.0, 10.0 ]
    kd: [   0.0,  0.0,  0.0 ]
    control_point: [ 0, 0, 0 ]
    goalpos: [ 0.45, -0.25, 0.30]
  - type: opspace::PureJPosTask
    name: task2
    kp: [  1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
    kd: [   0.0,  0.0,  0.0,  0.0,  0.0,  0.0]
    goalpos: [0.0, 0.0, 0.0, 0.0, 0.0, 1.57]

- skills:
  - type: opspace::TwoTaskSkill
    name: twotask
    slots:
      task1: task
      task2: task2
