- tasks:
  - type: opspace::PureCartPosTask
    name: task
    end_effector: 5
    kp: [   0.1,  0.1,  0.1 ]
    kd: [   0.0,  0.0,  0.0 ]
    control_point: [ 0, 0, 0 ]
    goalpos: [ 0.475, 0.05, 0.425]

- skills:
  - type: opspace::GenericSkill
    name: twotask
    slots:
      task: task
