- tasks:
  - type: opspace::TestPositionOrientationTask
    name: eepos
    end_effector_id: 5
    sigma_threshold: 0.005
    kp: [ 0.1, 0.1, 0.1, 0.1, 0.1, 0.1 ]
    kd: [ 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 ]
    goalpos: [ 0.5, 0.05, 0.5]
    goal_x: [ 1,  0,  0 ]
    goal_y: [ 0,  1,  0 ]
    goal_z: [ 0,  0,  1 ]
    
- skills:
  - type: opspace::GenericSkill
    name: GenericSkill
    slots:
      task: eepos
