- tasks:
  - type: opspace::TestImplicitSurfaceTask
    name: task
    end_effector: 5
    kp: [  0.1 ]
    kd: [   0.0 ]
    control_point: [ 0, 0, 0.05 ]
    R: 0.1
    T: 0.4
  - type: opspace::TestVelOriSurfaceTask
    name: task2
    end_effector: 5
    kp: [   0.1,  0.1, 0.1]
    kd: [   0.0,  0.0, 0.0 ]
    control_point: [ 0, 0, 0.05 ]
    R: 0.1
    T: 0.4

- skills:
  - type: opspace::TwoTaskSkill
    name: threetask
    slots:
      task1: task
      task2: task2
