- tasks:
  - type: opspace::TestImplicitSurfaceTask
    name: task
    end_effector: 5
    kp: [  0.1 ]
    kd: [   0.0 ]
    control_point: [ 0, 0, 0.05 ]
    R: 0.1
    T: 0.4
  - type: opspace::TestVelOriSurfaceTask
    name: task2
    end_effector: 5
    kp: [   0.1,  0.1, 0.1]
    kd: [   0.0,  0.0, 0.0 ]
    control_point: [ 0, 0, 0.05 ]
    R: 0.1
    T: 0.4
  - type: opspace::TestPureSelectCartPosTask
    name: task3
    end_effector: 5
    kp: [   0.1,  0.1 ]
    kd: [   0.0,  0.0 ]
    control_point: [ 0, 0, 0.05 ]
    goalpos: [0.475, 0.05]
    goalvel: [ 0.0, 0.0 ]
    selection: [1, 1, 0]

- skills:
  - type: opspace::ThreeTaskSkill
    name: threetask
    slots:
      task1: task
      task2: task2
      task3: task3
